--/print isChecked("Blessing of Freedom")
local locales={

--config: enemies engine
["Dynamic Targetting"]="动态目标",
["Target Dynamic Target"]="",
["Hostiles Only"]="",
["Wise Target"]="智能目标",
["Forced Burn"]="",
["Avoid Shields"]="",
["Tank Threat"]="",
["Safe Damage Check"]="",
["Don't break CCs"]="",
["Skull First"]="",
["Interrupt Only Whitelist"]="只打断白名单",
["Interrupts Handler"]="自动打断",
["Only Known Units"]="",
["Crowd Control"]="",
["Enrages Handler"]="",

--config: general
["Auto Delay"]="自动延时",
["Bot Update Rate"]="BR执行频率",
["Start/Stop BadRotations"]="开始/停止BR",
["Rotation Log"]="循环日志",
["Display Failcasts"]="",
["Queue Casting"]="",
["Auto Loot"]="自动拾取",
["Auto-Sell/Repair"]="自动售卖/修理",
["Accept Queues"]="自动接受队列",
["Overlay Messages"]="",
["Talent Anywhere"]="随便改天赋",
["Notify Not Unlocked"]="未解锁通知",
["Reset Options"]="重置选项",
["Reset Saved Profiles"]="重置保存的配置",

--config: healing engine
["HE Active"]="",
["Heal Pets"]="",
["Special Heal"]="",
["Sorting with Role"]="",
["Prioritize Special Targets"]="",
["Blacklist"]="",
["Prioritize Tank"]="",
["Prioritize Debuff"]="",
["Ignore Absorbs"]="",
["Incoming Heals"]="",
["Overhealing Cancel"]="",
["Dispel delay"]="",
["Healer Line of Sight Indicator"]="",

--config: other features
["Profession Helper"]="",
["Prospect Ores"]="",
["Mill Herbs"]="",
["Disenchant"]="",
["Leather Scraps"]="",
["Lockboxes"]="",
["Debug Timers"]="",
--config: save/loading settings
["Load Prior Saved Settings"]="",



--br：base options
["Cast Debug"]="施法debug",
["Ignore Combat"]="自动开怪",
["Mute Queue"]="",
["Use Crystal"]="",
["Use Fel Focuser"]="",
["Use emp. Rune"]="",

--圣骑士：防护
["Blessing of Freedom"]="自由祝福",
["Taunt"]="嘲讽",
["Racial"]="种族技能",
["Trinkets HP"]="",
["Trinkets"]="",
["Seraphim"]="",
["Avenging Wrath"]="",
["Bastion of Light"]="",
["Pot/Stoned"]="",
["Ardent Defender"]="",
["Blinding Light - HP"]="盲目之光-HP",
["Blinding Light - AoE"]="盲目之光-AOE",
["Clease Toxin"]="",
["Divine Shield"]="圣盾术",
["Flash of Light"]="圣光闪现",
["Guardian of Ancient Kings"]="",
["Hammer of Justice - HP"]="制裁之锤-HP",
["Light of the Protector"]="",
["Hand of the Protector - Party"]="",
["Lay On Hands"]="",
["Lay on Hands Target"]="",
["Blessing of Protection"]="保护祝福",
["Blessing of Protection Target"]="保护祝福目标",
["Blessing Of Sacrifice"]="牺牲祝福",
["Blessing Of Sacrifice Target"]="牺牲祝福目标",
["Shield of the Righteous - HP"]="正义盾击-HP",
["Redemption"]="救赎",
["Blinding Light - INT"]="打断：盲目之光",
["Hammer of Justice - INT"]="打断：制裁之锤",
["Rebuke - INT"]="打断：责难",
["Avenger's Shield - INT"]="打断：复仇者之盾",
["Interrupt At"]="打断时机",
["Avenger's Shield"]="复仇者之盾",
["Consecration"]="奉献",
["Blessed Hammer"]="祝福之锤",
["Hammer of the Righteous"]="正义之锤",
["Judgment"]="审判",
["Shield of the Righteous"]="正义盾击",
["Rotation Mode"]="",
["Cooldown Mode"]="",
["Defensive Mode"]="",
["Interrupt Mode"]="",
["Pause Mode"]="",

--圣骑士：神圣
["OOC Healing"]="",
["Necrotic Rot"]="",
["Mastery bonus"]="",
["Pre-Pull Timer"]="",
["Beacon of Light"]="圣光道标",
["Beacon of Faith"]="信仰道标",
["Critical HP"]="",
["Divine Protection"]="保护祝福",
["Divine Shield + Aura of Sacrifice Key"]="圣盾术+牺牲：按键",
["Divine Shield + Hand Of Reckoning Key"]="圣盾术+清算之手：按键",
["Hammer of Justice"]="制裁之锤",
["Blinding Light"]="盲目之光",
["InterruptAt"]="打断时机",
["Trinket 1"]="饰品1",
["Min Trinket 1 Targets"]="",
["Trinket 2"]="饰品2",
["Min Trinket 2 Targets"]="",
["Lay on Hands"]="",
["BoP Target"]="",
["Blessing of Sacrifice"]="",
["BoS Target"]="",
["Avenging Wrath Targets"]="",
["Holy Avenger"]="",
["Holy Avenger Targets"]="",
["Aura Mastery"]="光环掌握",
["Aura Mastery Targets"]="光环掌握目标",
["FoL Tanks"]="",
["FoL Infuse"]="",
["Holy Light"]="圣光术",
["Holy Light Infuse"]="圣光灌注",
["Holy Shock"]="神圣震击",
["Bestow Faith"]="赋予信仰",
["Bestow Faith Target"]="赋予信仰目标",
["Light of the Martyr"]="殉道者之光",
["Moving LotM"]="",
["Cloak LotM"]="",
["Rule of Law"]="",
["RoL Targets"]="",
["Light of Dawn"]="黎明之光",
["LoD Targets"]="",
["Beacon of Virtue"]="美德道标",
["BoV Targets"]="",
["Holy Prism"]="神圣棱镜",
["Holy Prism Targets"]="棱镜目标",
["Light's Hammer"]="圣光之锤",
["Light's Hammer Targets"]="圣光之锤目标",
["Light's Hammer Key"]="神光之锤快捷键",
["Auto Focus target"]="",
["DPS"]="DPS",
["Holy Prism Damage"]="神圣棱镜",
["Light's Hammer Damage"]="圣光之锤",
["Judgement"]="审判",
["Holy Shock Damage"]="神圣震击",
["Crusader Strike"]="十字军打击",

--圣骑士：惩戒
["APL Mode"]="",
["DPS Testing"]="DPS测试",
["Opener"]="",
["Challenge Skin Helper"]="",
["Greater Blessing of Kings"]="强效王者祝福",
["Greater Blessing of Wisdom"]="强效智慧祝福",
["Hand of Freedom"]="自由祝福",
["Hand of Hinderance"]="",
["Divine Storm Units"]="",
["Hold For Judgment"]="",
["Artifact"]="",
["Potion"]="药水",
["Elixir"]="",
["Crusade"]="",
["Holy Wrath"]="神圣愤怒",
["Shield of Vengeance - CD"]="",
["Gunpowder Charge"]="",
["Heirloom Neck"]="",
["Eye for an Eye"]="以眼还眼",
["Shield of Vengeance"]="复仇之盾",
["Hammer of Justice - Legendary"]="",
["Justicar's Vengeance"]="",
["Rebuke"]="责难",

--恶魔猎手：浩劫
["Eye Beam Usage"]="",
["Units To AoE"]="",
["Hold Fel Rush Charge"]="",
["Vengeful Retreat"]="",
["Auto Fel Rush After Retreat"]="",
["Glide"]="",
["Legendary Ring"]="",
["Metamorphosis"]="",
["Draught of Souls"]="",
["Blur"]="",
["Darkness"]="",
["Chaos Nova - HP"]="",
["Chaos Nova - AoE"]="",
["Chaos Nova"]="",
["Disrupt"]="",
["Mover Mode"]="",

--恶魔猎手：复仇
["Immolation Aura"]="",
["Sigil of Flame"]="",
["Torment"]="",
["Consume Magic"]="",
["Fel Devastation"]="",
["Agi-Pot"]="",
["Flask / Crystal"]="",
["Legendary Ring"]="",
["Fiery Brand"]="",
["Demon Spikes"]="",
["Hold Demon Spikes"]="",
["Metamorphosis"]="",
["Sigil of Misery - HP"]="",
["Sigil of Misery - AoE"]="",
["Soul Barrier"]="",
["Disrupt"]="",
["Sigil of Silence"]="",
["Sigil of Misery"]="",
["Mover Mode"]="",

--牧师：戒律
["Light's Wrath"]="",
["Light's Wrath Targets"]="",
["Light's Wrath after Rapture"]="",
["Dispel Magic"]="",
["Mass Dispel"]="",
["Body and Soul"]="",
["Angelic Feather"]="",
["Fade"]="",
["Shining Force"]="",
["Psychic Scream"]="",
["Leap Of Faith"]="",
["Dominant Mind"]="",
["Resurrection"]="",
["Resurrection - Target"]="",
["Atonement HP"]="",
["Alternate Heal & Damage"]="",
["Power Word: Shield"]="",
["PW:S Target"]="",
["Shadow Mend"]="",
["Shadow Mend Emergency"]="",
["Shadow Mend Emergency Self"]="",
["Penance Heal"]="",
["Debuff Helper"]="",
["Clarity of Will"]="",
["Pain Suppression Tank"]="",
["Pain Suppression"]="",
["Power Word: Radiance"]="",
["PWR Targets"]="",
["Shadow Covenant"]="",
["Shadow Covenant Targets"]="",
["Halo"]="",
["Halo Targets"]="",
["Shadow Word: Pain/Purge The Wicked"]="",
["Schism"]="",
["Penance"]="",
["Power Word: Solace"]="",
["Smite"]="",
["Divine Star"]="",
["Halo Damage"]="",
["Mindbender"]="",
["Shadowfiend"]="",
["Shadowfiend Targets"]="",
["Disable CD during Speed: Slow"]="",
["Parasitic Fetter Dispel Helper"]="",
["Drink"]="",
["Pre-Pot Timer"]="",
["Pre-pull Opener"]="",
["Prolonged Pot"]="",
["Pro Pot Targets"]="",
["Mana Potion"]="",
["Power Infusion"]="",
["Power Infusion Targets"]="",
["Rapture when get Innervate"]="",
["Rapture"]="",
["Rapture Targets"]="",
["Power Word: Barrier"]="",
["PWB Targets"]="",
["Evangelism"]="",
["Evangelism Targets"]="",
["Atonement for Evangelism"]="",
["Shining Force - Int"]="",
["Psychic Scream - Int"]="",
["Quaking Palm - Int"]="",
["Healer Mode"]="",

--牧师：神圣
["Cast Timing Debug"]="",
["Body and Mind"]="",
["Minimum Mana to DPS"]="",
["Spam Group Heals Hotkey"]="",
["Guardian Spirit"]="",
["Guardian Spirit Tank Only"]="",
["Light of Tuure"]="",
["Light of Tuure Tank Only"]="",
["Arcane Torrent"]="",
["Desperate Prayer"]="",
["Prayer of Mending"]="",
["Prayer of Mending Pre-Stack"]="",
["Holy Word: Serenity"]="",
["Flash Heal"]="",
["Heal"]="",
["Renew"]="",
["Renew on Tanks"]="",
["Renew while moving"]="",
["Holy Word: Sanctify"]="",
["Holy Word: Sanctify Targets"]="",
["Prayer of Healing"]="",
["Prayer of Healing Targets"]="",
["Automatic Mass Dispel"]="",
["Mass Dispel Hotkey"]="",
["DPS Mode"]="",
["Cooldowns Mode"]="",
["Decurse Mode"]="",


--牧师：暗影
["PWS: Body and Soul"]="",
["Mouseover Dotting"]="",
["Shadow Crash"]="",
["SWP Max Targets"]="",
["VT Max Targets"]="",
["VT Dot HP Limit"]="",
["Int Pot"]="",
["Shadowfiend / Mindbender"]="",
["Shadowfiend Stacks"]="",
["Surrender To Madness"]="",
["Dispersion S2M"]="",
["Dispersion Stacks"]="",
["Power Infusion Stacks"]="",
["Void Torrent"]="",
["Void Torrent Stacks"]="",
["Dispersion"]="",
["Psychic Scream / Mind Bomb"]="",
["Silence"]="",
["Psychic Scream / Mind Bomb - Int"]="",
["Void Form Mode"]="",


--死亡骑士：鲜血
["Dark Command"]="",
["Dancing Rune Weapon"]="",
["Death and Decay"]="",
["Use Bonestorm"]="",
["Bonestorm Targets"]="",
["Bonestorm RP"]="",
["Death Strike High Prio"]="",
["Death Strike Low Prio"]="",
["Consumption VB"]="",
["Blood Boil High Prio"]="",
["Anti-Magic Shell"]="",
["Blooddrinker"]="",
["Vampiric Blood"]="",
["Icebound Fortitude"]="",
["Raise Ally"]="",
["Raise Ally - Target"]="",
["Asphyxiate"]="",
["Death Grip - Int"]="",
["Mind Freeze"]="",
["Interrupts"]="",

--死亡骑士：冰霜
["Death Grip"]="",
["Glacial Advance"]="",
["Path of Frost"]="",
["Remorseless Winter"]="",
["Breath Of Sindragosa Debug"]="",
["Breath of Sindragosa"]="",
["Empower Rune Weapon"]="",
["Frostwyrm's Fury"]="",
["Frostwyrm's Fury Units"]="",
["Horn of Valor"]="",
["Obliteration"]="",
["Pillar of Frost"]="",
["Healing Potion/Healthstone"]="",
["Blinding Sleet"]="",
["Death Strike"]="",
["Cleave Mode"]="",

--死亡骑士：邪恶
["SpellQueue Clear"]="",
["Auto Target"]="",
["Debug Info"]="",
["Dark Transformation"]="",
["Dark Transformation Units"]="",
["DnD Festering Wounds"]="",
["Summon Gargoyle"]="",
["Auto Summon"]="",
["Pet Attack"]="",
["Healthstone"]="",
["Corpse Shield"]="",
["Leap"]="",
["Asphyxiate Kick"]="",
["Necrotic Strike"]="",
["Chains of Ice"]="",
["Chains of Ice Focus"]="",
["AMS Counter"]="",
["Necro Spam"]="",
["Eye of Leotheras"]="",

--盗贼：奇袭/刺杀
["Stealth Breaker"]="",
["Fan of Knives"]="",
["Lethal Poison"]="",
["Non-Lethal Poison"]="",
["Poisoned Knife"]="",
["Stealth"]="",
["Shadowstep"]="",
["Tricks of the Trade on Focus"]="",
["Marked For Death"]="",
["Toxic Blade"]="",
["Vanish"]="",
["Vendetta"]="",
["Evasion"]="",
["Feint"]="",
["Cloak of Shadows"]="",
["Crimson Vial"]="",
["Kick"]="",
["Kidney Shot"]="",
["Pick Pocket Mode"]="",

--盗贼：狂徒
["Bribe"]="",
["Grappling Hook"]="",
["Sprint with Legendary Boots"]="",
["Pistol Shot - Out of Range"]="",
["Marked For Death - Precombat"]="",
["Blade Flurry"]="",
["Riposte"]="",
["Gouge"]="",
["Blind"]="",
["Parley"]="",
["Between the Eyes"]="",

--盗贼：敏锐
["SS Range"]="",
["Shuriken Toss OOR"]="",
["Shadow Blades"]="",
["Shadow Dance"]="",
["Shuriken Tornado"]="",
["Symbols of Death"]="",
["Nightblade Multidot"]="",
["PickPocket Mode"]="",

--武僧：踏风
["CJL OOR"]="",
["CJL OOR Cancel"]="",
["Roll"]="",
["Resuscitate"]="",
["Tiger's Lust"]="",
["Whirling Dragon Punch"]="",
["Provoke"]="",
["Spread Mark Cap"]="",
["SEF Timer"]="",
["SEF Behavior"]="",
["Energizing Elixir"]="",
["Touch of the Void"]="",
["Serenity"]="",
["Touch of Death"]="",
["Xuen"]="",
["Gnawed Thumb Ring"]="",
["Ring of Collapsing Futures"]="",
["Specter of Betrayal"]="",
["Vial of Ceaseless Toxins"]="",
["Vivify"]="",
["Detox"]="",
["Leg Sweep - HP"]="",
["Leg Sweep - AoE"]="",
["Touch of Karma"]="",
["Diffuse/Dampen"]="",
["Spear Hand Strike"]="",
["Paralysis"]="",
["Leg Sweep"]="",
["SEF Mode"]="",
["FSK Mode"]="",

--武僧：酒仙
["BoC Rotation"]="",
["Purifying Brew"]="",
["Stagger dmg % to purify"]="",
["Chi Burst Targets"]="",
["Exploding Keg Targets"]="",
["Breath of Fire Targets"]="",
["Keg Smash Targets"]="",
["Effuse"]="",
["Healing Elixir"]="",
["Fortifying Brew"]="",
["Dampen Harm"]="",
["Expel Harm"]="",
["Expel Harm Orbs"]="",
["Quaking Palm"]="",


--武僧：织雾
["Boss Helper"]="",
["Mana Tea"]="",
["Life Cocoon"]="",
["Thunder Focus Tea"]="",
["Renewing Mist"]="",
["Enveloping Mist"]="",
["Sheiluns Gift"]="",
["Essence Font"]="",
["EF Targets"]="",
["Revival"]="",
["Revival Targets"]="",
["Chi Ji"]="",
["Chi Ji Targets"]="",

--战士：武器
["AoE Threshold"]="",
["Battle Shout"]="",
["Berserker Rage"]="",
["Charge"]="",
["Hamstring"]="",
["Heroic Leap"]="",
["Heroic Leap - Target"]="",
["Heroic Charge"]="",
["Avatar"]="",
["Bladestorm"]="",
["Ravager"]="",
["Healthstone/Potion"]="",
["Defensive Stance"]="",
["Die by the Sword"]="",
["Intimidating Shout"]="",
["Rallying Cry"]="",
["Storm Bolt"]="",
["Victory Rush"]="",
["Pummel"]="",
["Intimidating Shoult - Int"]="",
["Storm Bolt - Int"]="",
["Heroic Mode"]="",

--战士：狂怒
["Bladestorm Units"]="",
["Piercing Howl"]="",
["Dragon Roar"]="",
["Recklessness"]="",
["Enraged Regeneration"]="",
["Intimidating Shout - Int"]="",

--战士：防护
["Artifact HP"]="",
["High Rage Revenge"]="",
["Str-Pot"]="",
["Battle Cry"]="",
["Demoralizing Shout - CD"]="",
["Shockwave"]="",
["Demoralizing Shout"]="",
["Last Stand"]="",
["Shield Wall"]="",
["Shockwave - HP"]="",
["Shockwave - Units"]="",
["Spell Reflection"]="",
["Shockwave - Int"]="",

--猎人

--萨满

--法师

--术士

--德鲁伊



}

local hooked = false
C_Timer.NewTicker(.5, function()
  if hooked then return;end
  if br and br.ui and br.ui.createCheckbox then
    hooked = true
    
    print("br 汉化开始")
    
    --修改多选框
    local original = br.ui.createCheckbox
    function br.ui.createCheckbox(parent, text, tooltip, checked)
      if tooltip and locales[tooltip] and locales[tooltip]~="" then
        tooltip = locales[tooltip]
      elseif locales[tooltip]==nil then      
        print('["'..tooltip..'"]="",')
      end
      return original(parent, text, tooltip, checked)
    end
    
    --修改按钮文字
    
    --修改下拉框
    
    --支持中文字体
    DiesalFontNormal:SetFont("Interface\\AddOns\\BadRotations_CN\\fonts\\ARKai_T.ttf",11 )
    DiesalFontPixel:SetFont("Interface\\AddOns\\BadRotations_CN\\fonts\\ARKai_T.ttf", 8 )
    DiesalFontPixelOutLine:SetFont( "Interface\\AddOns\\BadRotations_CN\\fonts\\ARKai_T.ttf", 8, "OUTLINE, MONOCHROME" )
    DiesalFontPixel2:SetFont( "Interface\\AddOns\\BadRotations_CN\\fonts\\ARKai_T.ttf", 8, "OUTLINE, MONOCHROME" )
    print("br 汉化完成")
  end
end)
